# Project-wide Gradle settings.
kotlin.code.style=official
android.nonTransitiveRClass=true

# Enable Caching and Parallel Builds
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.workers.max=4

# Kotlin & KSP Configurations
kotlin.compiler.execution.strategy=in-process
ksp.incremental=false

# Jetifier (Must be true or false)
android.enableJetifier=false

# Allow missing google-services.json
googleServices.missing.passthrough=true

# JVM Options (Unified for Headless Linux Runner)
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8 -Djava.awt.headless=true
